server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://192.168.1.193:3306/zhiyu?&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com\axy\zhiyu\mapper\xml\*.xml





