server:
  port: 80
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com\axy\zhifu\mapper\xml\*.xml

axy:
  config:
    salt: ZhiYu2020
    tokenKey: ZhiYuYuLeZhiYuYuLeZhiYuYuLeZhiYuYuLe

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///zhongfu?&serverTimezone=GMT&characterEncoding=UTF-8
    password: rootadmin
    username: root